// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: service.proto

package qubicpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QubicService_GetBasicInfo_FullMethodName           = "/qubic.v1.QubicService/GetBasicInfo"
	QubicService_GetBetInfo_FullMethodName             = "/qubic.v1.QubicService/GetBetInfo"
	QubicService_GetActiveBets_FullMethodName          = "/qubic.v1.QubicService/GetActiveBets"
	QubicService_GetActiveBetsByCreator_FullMethodName = "/qubic.v1.QubicService/GetActiveBetsByCreator"
	QubicService_GetBettorsByBetOption_FullMethodName  = "/qubic.v1.QubicService/GetBettorsByBetOption"
)

// QubicServiceClient is the client API for QubicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QubicServiceClient interface {
	GetBasicInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BasicInfo, error)
	GetBetInfo(ctx context.Context, in *GetBetInfoRequest, opts ...grpc.CallOption) (*BetInfo, error)
	GetActiveBets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ActiveBets, error)
	GetActiveBetsByCreator(ctx context.Context, in *GetActiveBetsByCreatorRequest, opts ...grpc.CallOption) (*ActiveBets, error)
	GetBettorsByBetOption(ctx context.Context, in *GetBettorsByBetOptionRequest, opts ...grpc.CallOption) (*BetOptionBettors, error)
}

type qubicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQubicServiceClient(cc grpc.ClientConnInterface) QubicServiceClient {
	return &qubicServiceClient{cc}
}

func (c *qubicServiceClient) GetBasicInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BasicInfo, error) {
	out := new(BasicInfo)
	err := c.cc.Invoke(ctx, QubicService_GetBasicInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qubicServiceClient) GetBetInfo(ctx context.Context, in *GetBetInfoRequest, opts ...grpc.CallOption) (*BetInfo, error) {
	out := new(BetInfo)
	err := c.cc.Invoke(ctx, QubicService_GetBetInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qubicServiceClient) GetActiveBets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ActiveBets, error) {
	out := new(ActiveBets)
	err := c.cc.Invoke(ctx, QubicService_GetActiveBets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qubicServiceClient) GetActiveBetsByCreator(ctx context.Context, in *GetActiveBetsByCreatorRequest, opts ...grpc.CallOption) (*ActiveBets, error) {
	out := new(ActiveBets)
	err := c.cc.Invoke(ctx, QubicService_GetActiveBetsByCreator_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qubicServiceClient) GetBettorsByBetOption(ctx context.Context, in *GetBettorsByBetOptionRequest, opts ...grpc.CallOption) (*BetOptionBettors, error) {
	out := new(BetOptionBettors)
	err := c.cc.Invoke(ctx, QubicService_GetBettorsByBetOption_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QubicServiceServer is the server API for QubicService service.
// All implementations must embed UnimplementedQubicServiceServer
// for forward compatibility
type QubicServiceServer interface {
	GetBasicInfo(context.Context, *emptypb.Empty) (*BasicInfo, error)
	GetBetInfo(context.Context, *GetBetInfoRequest) (*BetInfo, error)
	GetActiveBets(context.Context, *emptypb.Empty) (*ActiveBets, error)
	GetActiveBetsByCreator(context.Context, *GetActiveBetsByCreatorRequest) (*ActiveBets, error)
	GetBettorsByBetOption(context.Context, *GetBettorsByBetOptionRequest) (*BetOptionBettors, error)
	mustEmbedUnimplementedQubicServiceServer()
}

// UnimplementedQubicServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQubicServiceServer struct {
}

func (UnimplementedQubicServiceServer) GetBasicInfo(context.Context, *emptypb.Empty) (*BasicInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBasicInfo not implemented")
}
func (UnimplementedQubicServiceServer) GetBetInfo(context.Context, *GetBetInfoRequest) (*BetInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBetInfo not implemented")
}
func (UnimplementedQubicServiceServer) GetActiveBets(context.Context, *emptypb.Empty) (*ActiveBets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveBets not implemented")
}
func (UnimplementedQubicServiceServer) GetActiveBetsByCreator(context.Context, *GetActiveBetsByCreatorRequest) (*ActiveBets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveBetsByCreator not implemented")
}
func (UnimplementedQubicServiceServer) GetBettorsByBetOption(context.Context, *GetBettorsByBetOptionRequest) (*BetOptionBettors, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBettorsByBetOption not implemented")
}
func (UnimplementedQubicServiceServer) mustEmbedUnimplementedQubicServiceServer() {}

// UnsafeQubicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QubicServiceServer will
// result in compilation errors.
type UnsafeQubicServiceServer interface {
	mustEmbedUnimplementedQubicServiceServer()
}

func RegisterQubicServiceServer(s grpc.ServiceRegistrar, srv QubicServiceServer) {
	s.RegisterService(&QubicService_ServiceDesc, srv)
}

func _QubicService_GetBasicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QubicServiceServer).GetBasicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QubicService_GetBasicInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QubicServiceServer).GetBasicInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QubicService_GetBetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QubicServiceServer).GetBetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QubicService_GetBetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QubicServiceServer).GetBetInfo(ctx, req.(*GetBetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QubicService_GetActiveBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QubicServiceServer).GetActiveBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QubicService_GetActiveBets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QubicServiceServer).GetActiveBets(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QubicService_GetActiveBetsByCreator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveBetsByCreatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QubicServiceServer).GetActiveBetsByCreator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QubicService_GetActiveBetsByCreator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QubicServiceServer).GetActiveBetsByCreator(ctx, req.(*GetActiveBetsByCreatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QubicService_GetBettorsByBetOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBettorsByBetOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QubicServiceServer).GetBettorsByBetOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QubicService_GetBettorsByBetOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QubicServiceServer).GetBettorsByBetOption(ctx, req.(*GetBettorsByBetOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QubicService_ServiceDesc is the grpc.ServiceDesc for QubicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QubicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qubic.v1.QubicService",
	HandlerType: (*QubicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBasicInfo",
			Handler:    _QubicService_GetBasicInfo_Handler,
		},
		{
			MethodName: "GetBetInfo",
			Handler:    _QubicService_GetBetInfo_Handler,
		},
		{
			MethodName: "GetActiveBets",
			Handler:    _QubicService_GetActiveBets_Handler,
		},
		{
			MethodName: "GetActiveBetsByCreator",
			Handler:    _QubicService_GetActiveBetsByCreator_Handler,
		},
		{
			MethodName: "GetBettorsByBetOption",
			Handler:    _QubicService_GetBettorsByBetOption_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
